# Generated by Django 4.2.3 on 2023-07-06 04:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('capacity', models.IntegerField(default=0)),
                ('info', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'school_class_model',
            },
        ),
        migrations.CreateModel(
            name='SchoolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('info', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'school_model',
            },
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('date_of_birth', models.DateField(default=datetime.datetime.now)),
                ('photo', models.ImageField(blank=True, upload_to='Teacher_photo/%Y/%m/%d')),
                ('degree', models.CharField(max_length=50)),
                ('salary', models.IntegerField(default=0)),
                ('phone_number', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('password', models.CharField()),
                ('tclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundalik.schoolclassmodel')),
                ('tschool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundalik.schoolmodel')),
            ],
            options={
                'db_table': 'teacher_model',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('grade', models.CharField(default='ordinary')),
                ('age', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, upload_to='Student_photo/%Y/%m/%d')),
                ('date_of_birth', models.DateField(default=datetime.datetime.now)),
                ('address', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField()),
                ('sclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundalik.schoolclassmodel')),
                ('sschool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundalik.schoolmodel')),
                ('steacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundalik.teachermodel')),
            ],
            options={
                'db_table': 'student_model',
            },
        ),
        migrations.AddField(
            model_name='schoolclassmodel',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kundalik.schoolmodel'),
        ),
    ]
